# Site settings
title: Cyber Security
description: "A minimal blog template, build with Jekyll."
url: "https://rufan0.github.io/blog/"
author:
  name: "Rufan"
  email: "b.rufan3@gmail.com"
  url: "https://rufan0.github.io"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
