# Site settings
title: Cyber Security
description: "A minimal blog template, build with Jekyll."
url: "https://rufan0.github.io/blog/"
author:
  name: "Rufan"
  email: "b.rufan3@gmail.com"
  url: "https://rufan0.github.io"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Rufan0
  instagram:
  linkedin: rufan-bayramzad…ô-80b6621a7
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 0rufn
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/